config/routes.rb
Karma::Application.routes.draw do
  mount RailsAdmin::Engine => '/admin', :as => 'rails_admin'

  resources :notes
  resources :notecollections
  
  devise_scope :user do
    delete 'users/sign_out' => 'session#destroy', :as => 'user_sign_out'
  end

  devise_for :users,  :controllers => {:omniauth_callbacks => "omniauth_callbacks"}
  
  post 'notes/new/collection/:collection_id' => 'notes#pass', :as => 'collection_pass'
  get 'notes/new/collection/:collection_id' => 'notes#pass_new', :as => 'collection_pass_new'
  match 'tag/:hashtag', :to => "home#tag_search"
  get 'note/:note_id' => 'notecollections#show_note', :as => 'collection_show_note'
  resources :users

  root :to => "home#index"
  match 'home', :to => "home#index"
  match 'map', :to => "home#map"
  match 'seed', :to => "shouts#seed"
  match 'privacy', :to => "home#privacy"
  match 'logs/development', :to => "logs#development"
  match 'logs/production', :to => "logs#production"

end

app/models/notecollection.rb
class Notecollection
  include Mongoid::Document
  include Mongoid::Timestamps
  include Mongoid::Paranoia
  

  has_many :notes


  field :notes_list,			:type => Array, :default => []

  def notes_count
    self.notes.count
  end


end

app/controllers/notecollections_controller.rb
class NotecollectionsController < ApplicationController
  # GET /notecollections
  # GET /notecollections.json
  def index
    @notecollections = Notecollection.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @notecollections }
    end
  end

  # GET /notecollections/1
  # GET /notecollections/1.json
  def show
    @notecollection = Notecollection.find(params[:id])
    @notes = @notecollection.notes.desc(:time_created)

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @notecollection }
    end
  end

  def show_note
    @note = Note.find(params[:note_id])
    @notecollection = @note.notecollection #Notecollection.find(params[:collection_id])
    @all_notes = @notecollection.notes.desc(:time_created)

    user = User.where(_id: @note.user_receiver_id).first
    
    unless user
      user = Virtualuser.where(_id: @note.user_receiver_id).first
    end

    @notes_json = {
      :collection => @notecollection,
      :config => {
        :default_note_id => @note._id,
        :default_note_index => @note.note_index
      },
      :notes => @all_notes,
      :user => user
    }.to_json
    respond_to do |format|
      format.html # show.html.erb
      format.json { render  :status => 200,
                            :json => { :success => true,
                            :info => "Collection pulled succesfully.",
                            :data => {  :collection => @notecollection,
                                        :config => {:default_note_id => @note._id, :default_note_index => @note.note_index},
                                        :notes => @all_notes} }}



    end
  end
  # GET /notecollections/new
  # GET /notecollections/new.json
  def new
    @notecollection = Notecollection.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @notecollection }
    end
  end

  # GET /notecollections/1/edit
  def edit
    @notecollection = Notecollection.find(params[:id])
  end

  # POST /notecollections
  # POST /notecollections.json
  def create
    @notecollection = Notecollection.new(params[:notecollection])

    respond_to do |format|
      if @notecollection.save
        format.html { redirect_to @notecollection, notice: 'Notecollection was successfully created.' }
        format.json { render json: @notecollection, status: :created, location: @notecollection }
      else
        format.html { render action: "new" }
        format.json { render json: @notecollection.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /notecollections/1
  # PUT /notecollections/1.json
  def update
    @notecollection = Notecollection.find(params[:id])

    respond_to do |format|
      if @notecollection.update_attributes(params[:notecollection])
        format.html { redirect_to @notecollection, notice: 'Notecollection was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @notecollection.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /notecollections/1
  # DELETE /notecollections/1.json
  def destroy
    @notecollection = Notecollection.find(params[:id])
    @notecollection.destroy

    respond_to do |format|
      format.html { redirect_to notecollections_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/notecollections_helper.rb
module NotecollectionsHelper
end

app/views/notecollections/_form.html.erb
<%= form_for(@notecollection) do |f| %>
  <% if @notecollection.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@notecollection.errors.count, "error") %> prohibited this notecollection from being saved:</h2>

      <ul>
      <% @notecollection.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/notecollections/edit.html.erb
<h1>Editing notecollection</h1>

<%= render 'form' %>

<%= link_to 'Show', @notecollection %> |
<%= link_to 'Back', notecollections_path %>

app/views/notecollections/index.html.erb
<h1>Listing notecollections</h1>

<table>
  <tr>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @notecollections.each do |notecollection| %>
  <tr>
    <td><%= link_to 'Show', notecollection %></td>
    <td><%= link_to 'Edit', edit_notecollection_path(notecollection) %></td>
    <td><%= link_to 'Destroy', notecollection, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Notecollection', new_notecollection_path %>

app/views/notecollections/new.html.erb
<h1>New notecollection</h1>

<%= render 'form' %>

<%= link_to 'Back', notecollections_path %>

app/views/notecollections/show.html.erb
<p id="notice"><%= notice %></p>

<% @notes.each do |note| %>
	<%= note.user_giver.displayname %> gave to <%= note.user_receiver.displayname %> and said <%= note.content %><br/>
<% end %>

<%= link_to 'Edit', edit_notecollection_path(@notecollection) %> |
<%= link_to 'Back', notecollections_path %>

app/views/notecollections/show_note.html.erb
<div
  ng-controller="NoteController"
  class="note"
  data-notes-json="<%= @notes_json %>"
>
  <div class="header">
    
    <div class="home__column">
    <i
      class="fa fa-arrow-circle-o-left back-button"
      ng-click="goToHome()"
    ></i>
      <h2 class="header__text">THREDYOU: (name to name)</h2>
    </div>

  </div>

  <div class="content">
    <div
      tf-map
      tf-map-lat=""
      class="note__map"
    >
    </div>

    <div class="note__main">

      <p id="notice"><%= notice %></p>

      <div class="note__content">
        <div
          class="note__content__item"
          ng-show="!state.showSendForm"
        >
          What the
        </div>
        <div
          class="note__content__send-form"
          ng-show="state.showSendForm"
        >
          <button
            ng-click="sendNote()"
          >
            Thred someone in
          </button>
        </div>
      </div>

      <div class="note__nav">

        <button
          class="note__nav__button--previous"
          ng-class="state.hasPreviousNote | false: 'note__nav__button--disabled'"
          ng-click="showPreviousNote()"
        >
          <i class="fa fa-caret-left note__nav__button__arrow--previous"></i>
          <div class="note__nav__button__line"></div>
        </button>

        <div class="note__nav__title">
          <p>Matt thredded you in</p>
          <p><i>{{currentNote.created_at | date:'longDate'}}</i></p>
        </div>

        <button
          class="note__nav__button--next"
          ng-class="state.hasNextNote || state.isNextNoteTheSendForm | false: 'note__nav__button--disabled'"
          ng-click="showNextNote()"
        >
          <i class="fa fa-caret-right note__nav__button__arrow--next"></i>
          <div class="note__nav__button__line"></div>
        </button>
      </div>

    </div>

  </div>
</div>