config/routes.rb
Karma::Application.routes.draw do
  mount RailsAdmin::Engine => '/admin', :as => 'rails_admin'

  resources :notes
  resources :notecollections
  
  devise_scope :user do
    delete 'users/sign_out' => 'session#destroy', :as => 'user_sign_out'
  end

  devise_for :users,  :controllers => {:omniauth_callbacks => "omniauth_callbacks"}
  
  post 'notes/new/collection/:collection_id' => 'notes#pass', :as => 'collection_pass'
  get 'notes/new/collection/:collection_id' => 'notes#pass_new', :as => 'collection_pass_new'
  match 'tag/:hashtag', :to => "home#tag_search"
  get 'note/:note_id' => 'notecollections#show_note', :as => 'collection_show_note'
  resources :users

  root :to => "home#index"
  match 'home', :to => "home#index"
  match 'map', :to => "home#map"
  match 'seed', :to => "shouts#seed"
  match 'privacy', :to => "home#privacy"
  match 'logs/development', :to => "logs#development"
  match 'logs/production', :to => "logs#production"

end

app/models/note.rb
class Note
  include Mongoid::Document
  include Mongoid::Timestamps
  include Mongoid::Paranoia
  include Mongoid::Paperclip
  include Mongoid::Search
  include Geocoder::Model::Mongoid
  
  reverse_geocoded_by :geoloc_rev
  reverse_geocoded_by :geoloc_rev do |obj,results|
    if geo = results.first
      obj.address     = geo.address
      obj.city        = geo.city
      obj.zipcode     = geo.postal_code
      
      obj.state       = geo.state
      # obj.state_code  = geo.state_code

      obj.country     = geo.country_code
    end
  end

  before_validation :reverse_geoloc #, :factual_check
  after_validation :reverse_geocode  # auto-fetch address

  before_save :extract_hashtags
  

  belongs_to  :notecollection
  belongs_to  :user_giver, :class_name => "User", :inverse_of => :note_givens#, :foreign_key => "giver_id" 
  belongs_to  :user_receiver, :class_name => "User", :inverse_of => :note_receiveds#, :foreign_key => "receiver_id"
  has_and_belongs_to_many   :virtualusers

  has_many    :tags
  search_in   :tags => :name

  acts_as_gmappable :position => :geoloc, :process_geocoding => false
    

  # properties

  field :content,                 :type => String, :default => ""
  field :note_index,              :type => Integer, :default => 0

  field :is_private_name_giver,      :type => Boolean, :default => false
  field :is_private_content_giver,   :type => Boolean, :default => false
  field :is_private_picture_giver,   :type => Boolean, :default => false

  field :is_private_name_receiver,    :type => Boolean, :default => false
  field :is_private_content_receiver,   :type => Boolean, :default => false
  field :is_private_picture_receiver,   :type => Boolean, :default => false

  field :expiration,                :type => Integer, :default => 1209600 # 2 weeks in seconds
  
  field :geoloc,                    :type => Array, :default => []
  field :geoloc_rev,                :type => Array, :default => []
  field :address,                 :type => String, :default => ""
  field :city,                    :type => String, :default => ""
  field :state,                   :type => String, :default => ""
  field :sate_code,               :type => String, :default => ""
  field :zipcode,                 :type => String, :default => ""
  field :country,                 :type => String, :default => ""

  field :flag,                    :type => String, :default => ""
  field :gmaps,                   :type => Boolean

  attr_accessor :email, :phone_number, :displayname, :user_code, :find_type
  
  # field :expiration_time, :type => Time, :default => Time.now +1.day

  def next_note
  end

  def gmaps4rails_address
    #describe how to retrieve the address from your model, if you use directly a db column, you can dry your code, see wiki
    # "#{self.street}, #{self.city}, #{self.country}" 
  end

  def reverse_geoloc
    self.geoloc_rev = self.geoloc.reverse
  end

  def factual_check
    factual = Factual.new("xe6ym5IVW4QUWpKyEOhhWnYSYTUv6TAmI4GAKa5h", "xxcdSNzLIrrOVwYYrVO6pNobGCUSeEjj4f6KaVgH")
    # query = factual.geopulse(self.geoloc[0],self.geoloc[1]).select("race_and_ethnicity")

    query = factual.table("places").limit(1).geo("$point" => self.geoloc)
  
    logger.info(query.to_a)
  end

  index({geoloc: "2d"})

  IMAGE_SIZES = { :small => "150x150>" ,
        :preview => "200x200>",
        :large => "250x250>",
        :xlarge => "400x400>"}    
    
    has_mongoid_attached_file :picture, :styles => IMAGE_SIZES,
      :storage => :s3,
      :s3_credentials => "#{Rails.root}/config/s3.yml",
      :path => ":class/:id/:style.:extension",
      :bucket => "picture_#{Rails.env}"
      
    
    validates_attachment_size :picture, :less_than => 10.megabytes
    validates_attachment_content_type :picture, :content_type => ['image/gif', 'image/png', 'image/x-png', 'image/jpeg', 'image/pjpeg', 'image/jpg']  


    def check_receiver
      read_attribute(:user_receiver).presence || ""
    end

    def extract_hashtags
      
      hashtag_regex = /\#\w\w+/
      hashtags = self.content.scan(hashtag_regex)
      hashtags.each do |hashtag|
        self.tags << Tag.new(:name => hashtag)
      end
    end


end

app/controllers/notes_controller.rb
class NotesController < ApplicationController
  # GET /notes
  # GET /notes.json
  def index
    @notes = Note.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @notes }
    end
  end

  # GET /notes/1
  # GET /notes/1.json
  def show
    @note = Note.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @note }
    end
  end

  # GET /notes/new
  # GET /notes/new.json
  def new
    @note = Note.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @note }
    end
  end

  # GET /notes/1/edit
  def edit
    @note = Note.find(params[:id])
  end

  # POST /notes
  # POST /notes.json
  def create
    @notecollection = Notecollection.new()
    @note = Note.new(params[:note].merge({:notecollection_id => @notecollection._id, :note_index => 0}))
    @notecollection.notes_list[0] = @note._id.to_s
    @note.user_giver = current_user

    case params[:note][:find_type]
    when "email"
      
      user = User.where(email: params[:note][:email]).first
      unless user
        user = Virtualuser.where(email: params[:note][:email]).first_or_initialize
        @note.add_to_set(:virtualuser_ids, user._id)
        user.receive_count += 1
        user.save
      end
      
      @note.user_receiver = user
      user.receive_count += 1
      user.save

    when "phone_number"
      
      user = User.where(phone_number: params[:phone_number]).first
      
      unless user
        user = Virtualuser.where(phone_number: params[:phone_number]).first_or_initialize
        @note.add_to_set(:virtualuser_ids, user._id)
        user.receive_count += 1
        user.save
        
      end
      
      @note.user_receiver = user
      user.receive_count += 1
      user.save
    else
    end

    respond_to do |format|
      if @note.save
        @notecollection.save
        current_user.give_count += 1
        current_user.save

        format.html { redirect_to @note, notice: 'Note was successfully created.' }
        format.json { render json: @note, status: :created, location: @note }
      else
        format.html { render action: "new" }
        format.json { render json: @note.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /notes/1
  # PUT /notes/1.json
  def update
    @note = Note.find(params[:id])

    respond_to do |format|
      if @note.update_attributes(params[:note])
        format.html { redirect_to @note, notice: 'Note was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @note.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /notes/1
  # DELETE /notes/1.json
  def destroy
    @note = Note.find(params[:id])
    @note.destroy

    respond_to do |format|
      format.html { redirect_to notes_url }
      format.json { head :no_content }
    end
  end

  def pass_new
    @notecollection = params[:collection_id]
    @note = Note.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @note }
    end
  end

  def pass
    @notecollection_id = params[:collection_id]    
    @note = Note.new(params[:note].merge({:notecollection_id => @notecollection_id}))
    @notecollection = Notecollection.find(@notecollection_id)
    @notecollection.notes_list << @note._id.to_s
    @notecollection.save
    @note.note_index = @notes_collection.notes_list.size
    @note.user_giver = current_user

    case params[:note][:find_type]
    when "email"
      
      user = User.where(email: params[:note][:email]).first
      unless user
        user = Virtualuser.where(email: params[:note][:email]).first_or_initialize
        @note.add_to_set(:virtualuser_ids, user._id)
        user.receive_count += 1
        user.save
      end
      @note.user_receiver = user
      user.receive_count += 1
      user.save

    when "phone_number"
      
      user = User.where(phone_number: params[:phone_number]).first
      
      unless user
        user = Virtualuser.where(phone_number: params[:phone_number]).first_or_initialize
        @note.add_to_set(:virtualuser_ids, user._id)
        user.receive_count += 1
        user.save
        
      end
      @note.user_receiver = user
      user.receive_count += 1
      user.save
    else
    end

    respond_to do |format|
      if @note.save
        
        current_user.give_count += 1
        current_user.save
        
        format.html { redirect_to @note, notice: 'Note was successfully created.' }
        format.json { render json: @note, status: :created, location: @note }
      else
        format.html { render action: "new" }
        format.json { render json: @note.errors, status: :unprocessable_entity }
      end
    end
  end

end

app/helpers/notes_helper.rb
module NotesHelper
end

app/views/notes/_form.html.erb
<%= form_for(@note) do |f| %>
  <% if @note.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@note.errors.count, "error") %> prohibited this note from being saved:</h2>

      <ul>
      <% @note.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :email %><br />
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <%= f.label :find_type %><br />
    <%= f.text_field :find_type %>
  </div>
  
  <div class="field">
    <%= f.label :phone_number %><br />
    <%= f.text_field :phone_number %>
  </div>

  <div class="field">
    <%= f.label :content %><br />
    <%= f.text_field :content %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/notes/_form_pass.html.erb
<%= form_for @note, :url => {:action => 'pass'} do |f| %>
  <% if @note.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@note.errors.count, "error") %> prohibited this note from being saved:</h2>

      <ul>
      <% @note.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :email %><br />
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <%= f.label :find_type %><br />
    <%= f.text_field :find_type %>
  </div>
  
  <div class="field">
    <%= f.label :phone_number %><br />
    <%= f.text_field :phone_number %>
  </div>

  <div class="field">
    <%= f.label :content %><br />
    <%= f.text_field :content %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/notes/_infowindow.html.erb
<h1><%= note.content %></h1>
<h2>content: <%= note.geoloc %></h2>


app/views/notes/edit.html.erb
<h1>Editing note</h1>

<%= render 'form' %>

<%= link_to 'Show', @note %> |
<%= link_to 'Back', notes_path %>

app/views/notes/index.html.erb
<h1>Listing notes</h1>

<table>
  <tr>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @notes.each do |note| %>
  <tr>
    <td><%= note.content %>
    <td><%= link_to 'Show', note %></td>
    <td><%= link_to 'Edit', edit_note_path(note) %></td>
    <td><%= link_to 'Destroy', note, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Note', new_note_path %>

app/views/notes/new.html.erb
<h1>New note</h1>

<%= render 'form' %>

<%= link_to 'Back', notes_path %>

app/views/notes/pass_new.html.erb
<h1>New note</h1>

<%= render 'form_pass' %>

<%= link_to 'Back', notes_path %>

app/views/notes/show.html.erb
<div
  ng-controller="NoteController"
  class="note"
  data-notes="<%=  %>"
>

  <div
    tf-map
    tf-map-lat=""
    class="note__map"
  >
  </div>

  <div class="note__main">
    <p id="notice"><%= notice %></p>

    <%= @note.user_giver.displayname %> <%= @note.user_receiver.displayname unless @note.user_receiver.nil? %> <%= @note.content %><br/>
    <%= link_to @note.notecollection._id, :controller => "/notecollections", :action => "show", :id => @note.notecollection._id unless @note.notecollection %> 

    <%= link_to 'Edit', edit_note_path(@note) %> |
    <%= link_to 'Back', notes_path %>

    <div class="note__nav">

      <button
        class="note__nav__button--previous"
        ng-click="showPreviousNote()"
      >
        <i class="fa fa-caret-left note__nav__button__arrow--previous"></i>
        <div class="note__nav__button__line"></div>
      </button>

      <div class="note__nav__title">
        <p>Matt thanked you</p>
        <p><i>May 20, 2013</i></p>
      </div>

      <button
        class="note__nav__button--next"
        ng-click="showNextNote()"
      >
        <i class="fa fa-caret-right note__nav__button__arrow--next"></i>
        <div class="note__nav__button__line"></div>
      </button>
    </div>

  </div>

</div>